### ISSUE TITLE
[Enhancement] - Build mechanism to retrieve latest dockerapp file versions from console

### ISSUE THREAD

**Issue by jhrabi** [admpresales/nimbusapp#10]
@panama69 @jeff-kingston 

Thinking of something akin to nimbusapp list , this would list all dockerapp projects from a given repository (default would be admpresales). 

This would call out to the Docker API and retrieve all the dockerapp files, and state their current (latest) versions. This way people wouldn't need to log into Docker Hub's GUI to determine the latest version. 

Thoughts?

**Comment by panama69** [comment]
agree.  i had played with a similar thought to be able to pull the latest image tag and update the app.config (env) entries a while back but had other priorities.

**Comment by jhrabi** [comment]
This will be resolved with pull #43
