### ISSUE TITLE
nimbusapp cannot be run offline

### ISSUE THREAD

**Issue by jhrabi** [admpresales/nimbusapp#14]
See https://github.com/docker/app/issues/412

This issue prevents docker app (and hence nimbusapp) from being used offline ATM. This has been broken since 0.5.0, as they changed how the docker-app files are stored since 0.4.1 and 0.5.0

Might need to come up with a way to commit the docker-app file locally if this isn't resolved.

J

**Comment by jasoncorlett** [comment]
Addressed in #17
