### ISSUE TITLE
Should nimbusapp version be 1.2.3 now?

### ISSUE THREAD

**Issue by msteffensen19** [admpresales/nimbusapp#31]
I previously (a few months ago) upgraded nimbusapp and it showed 1.2.2 with a date, possibly in May. Now, after running the upgrade again I still got version 1.2.2 but with the date 2019-09-04.

Did the version get missed somehow?

**Comment by jasoncorlett** [comment]
The 1.2.X series was first released in August. Versions 1.1.0 and 1.1.1 were released earlier this year.

Release history: https://github.com/admpresales/nimbusapp/releases

**Comment by msteffensen19** [comment]
When I last ran the nimbusapp upgrade, my nimbusapp --version displayed a release date in August and version 1.2.2. After I ran the upgrade it still said version 1.2.2 but with a the 2019-09-04 date. That's what I was wondering about - why should we have two dates for that same version?
