### ISSUE TITLE
Should nimbusapp ignore underscore params and display a message?

### ISSUE THREAD

**Issue by msteffensen19** [admpresales/nimbusapp#32]

**Comment by msteffensen19** [comment]
While I agree that folks should know that they don’t need to supply the underscore params BUT – they don’t know. And I’m I’m getting tired of handling emails where someone else didn’t understand.
Perhaps we could display a message educating them about it – and just strip off the underscore and anything past it.

So if you supply: $ nimbusapp autopass:10.9.0_d up

You might get a message: 
NIMBUSAPP: ignoring unnecessary underscore parameters - using 10.9.0

It would be easy to strip off the underscore and anything beyond it and this would educate folks that they don't need to supply the underscore params.

**Comment by jasoncorlett** [comment]
We could implement warning messages when users include common modifiers (`_d`, `_di` ans so on), but I would rather the script not change the tag. This would allow the user to learn what went wrong, and correct their command.

**Comment by msteffensen19** [comment]
I'm fine with that compromise - warn users that they supplied an underscore and params and they aren't need and suggest they remove them.

**Comment by jhrabi** [comment]
The warning would not be a suggestion to remove them. It would fail and tell them they should try it without the _d / _di tag. This would force them to learn the new behaviour instead of suggesting they learn it

**Comment by jhrabi** [comment]
So this wouldn't be a warning message at all. It'd be an error message with more in-depth information.

**Comment by msteffensen19** [comment]
That works for me and it's better than the current method which tries to run the commands and fails with some obscure messages.

**Comment by jasoncorlett** [comment]
Closing, addressed in PR #36
