### ISSUE TITLE
Incorrect ":" parsing in "Image:Version" pair on Mac's

### ISSUE THREAD

**Issue by vkuvaev** [admpresales/nimbusapp#34]
Hi Team, 
to also support this utility on Macs could you please fix this issue:

on line 404:
`IFS=: read IMAGE VERSION <<< $IMAGE`
should be quoted like 
`IFS=: read IMAGE VERSION <<< "$IMAGE"`
The same could be valid for similar lines using pipe 68, 90, 227, 400.

Otherwise Mac interprets `:` symbol as a delimiter after here-string `<<<` and changes it to `space`. Next `read` with `:` as a delimiter reads input incorrectly into single variable. Colon is a kind of special character in Mac
For linux, verified in ubuntu, this change is transparent.

**Reproduced** issue in Mac:
```
$ IFS=: read IMAGE VERSION <<< Octane:15.00.00.00;echo "IMAGE:$IMAGE" ;echo "VERSION:$VERSION"
IMAGE:Octane 15.00.00.00              <----Error
VERSION:                              <----Error
$ IFS=: read IMAGE VERSION <<< "Octane:15.00.00.00";echo "IMAGE:$IMAGE" ;echo "VERSION:$VERSION"
IMAGE:Octane
VERSION:15.00.00.00
$ IFS=/ read IMAGE VERSION <<< Octane/15.00.00.00;echo "IMAGE:$IMAGE" ;echo "VERSION:$VERSION" 
IMAGE:Octane
VERSION:15.00.00.00
```
Any way is fine for Ubuntu:
```
$ IFS=: read IMAGE VERSION <<< "Octane:15.00.00.00";echo "IMAGE:$IMAGE" ;echo "VERSION:$VERSION"
IMAGE:Octane
VERSION:15.00.00.00
$ IFS=: read IMAGE VERSION <<< Octane:15.00.00.00;echo "IMAGE:$IMAGE" ;echo "VERSION:$VERSION"
IMAGE:Octane
VERSION:15.00.00.00
```

**Comment by jasoncorlett** [comment]
Hi @vkuvaev,

Thank you for submitting this issue! Quoting for here-strings has been fixed as of PR #36, and in release 1.3.1.

I am closing this issue, please feel free to re-open if the fix does not work in your environment.
