### ISSUE TITLE
[Feature] Supporting latest *.dockerapp through nimbusapp

### ISSUE THREAD

**Issue by jhrabi** [admpresales/nimbusapp#4]
@panama69 @hpe-bryancole 

Dave's init script was designed to basically let him use the latest and greatest version of a container, by creating a env file (later turned to apps.config) where the declared version would be, so he wouldn't have to remember it. This is basically what the latest tag in Docker is specifically designed to do. We didn't want to utilize it with our containers because people had a hard time determining what version of the container was going to be spun up using latest. But with the dockerapp, it can be quickly rendered to see what version of the containers (services) are going to be run. 

What docker-app would require is a mechanism to update it's dockerapp file (something like app-pull) to update it's dockerapp file. 

I don't know if latest is something we want to support or not, but this is why I wanted to start this discussion

**Comment by panama69** [comment]
@jhrabi @hpe-bryancole 
so it sounds like you are making the argument to go to using the latest tag.

the question would be what gets displayed as the image name when a 'docker ps' is done?

If it shows the full image name like admpresales/devops:1.1.5.2 then I don't see a problem.  if it doesn't, then that would be a problem as i know several SA's who don't throw away or update their containers regularly and only do so when they are forced.

Without the full image name, we would run into the same difficulties when trying to triage any issues with the SA.

**Comment by jhrabi** [comment]
The latest tag still remains a double-edge sword, and I really think it should ONLY be used for people who understand it. Latest tags never get automatically pulled after their initial pull, so really it's only there for power users. But yes, a docker ps would show the actual running versions of the containers. The only thing that would have a latest tag would be the dockerapp images themselves, who contain the actual image data. Basically, Latest would replace the apps.config functinonality of nimbusapp.

**Comment by panama69** [comment]
@jhrabi @hpe-bryancole 
as discuss, let's not use the latest for now and continue based on our current approach.

plus, this will save development time and retraining of the field.
