### ISSUE TITLE
[Enhancement] - Determine easiest way to upgrade nimbusapp on next release

### ISSUE THREAD

**Issue by jhrabi** [admpresales/nimbusapp#7]
Figure out how to easily upgrade nimbusapp to latest release, potentially seeing if we can use pip to grab the latest release. 

Other possibility is to add a nimbusapp update or upgrade feature to check if there's a newer version.

Also open to other recommendations.

**Comment by jhrabi** [comment]
@jasoncorlett  How hard would it be to implement the script into upgrade functionality into Nimbus App itself? Alternatively, is there any other path we could go down or is our current upgrade path the best? Trying to see if we should close this or not.

**Comment by jasoncorlett** [comment]
@jhrabi How hard depends on "how robust". I'm fine with the current upgrade process and we'll hopefully supplement that with more frequent and robust Ansible pushes.

**Comment by jasoncorlett** [comment]
Closing this issue, I believe the current process is adequate
